<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>D365.Plugins</AssemblyName>
    <RootNamespace>D365.Plugins</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Dataverse / CRM SDK -->
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.49" />
    <PackageReference Include="Microsoft.CrmSdk.Workflow"       Version="9.0.2.49" />
  </ItemGroup>

</Project>
